image: rafmaia/node-sass

stages:
  - build
  - deploy

build:sass:
  stage: build
  allow_failure: false
  before_script:
    - npm i
  script: npm run build:css
  cache:
    key: dist
    policy: push
    paths:
      - ./
  artifacts:
    name: '$CI_JOB_NAME-$CI_COMMIT_REF_NAME'
    when: always
    expire_in: 1 day
    paths:
      - ./

deploy:develop: &deploy
  stage: deploy
  variables:
    CNAME: ttrip-develop.surge.sh
  cache:
  before_script:
    - npm install -g surge
  script: surge --project . --domain ${CNAME}
  environment:
    name: develop
    url: https://${CNAME}
  only:
    - develop

deploy:production:
  <<: *deploy
  variables:
    CNAME: ttrip.surge.sh
  environment:
    name: production
  only:
    - master
